from aoc.day08 import solve_part1, solve_part2

input_data = """\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


def test_solve_part1():
    assert solve_part1(input_data) == 14


def test_solve_part2():
    assert solve_part2(input_data) == 34
